services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: chatverse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_INITDB_ARGS: "--lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatverse-network
    deploy:
      resources:
        limits:
          memory: 512M  # Максимальный объем памяти
        reservations:
          memory: 256M  # Минимальный объем памяти

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatverse-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatverse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
    depends_on:
      - postgres
    ports:
      - "8080:8080" # Проброс порта приложения
    networks:
      - chatverse-network
    deploy:
      resources:
        limits:
          memory: 512M  # Максимальный объем памяти
        reservations:
          memory: 256M  # Минимальный объем памяти

volumes:
  postgres_data:
    driver: local

networks:
  chatverse-network:
    driver: bridge