apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: chatverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1001  # Добавляем группу для доступа к volume
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8.2-debian-11-r0
          securityContext:
            runAsUser: 1001  # Явно указываем пользователя
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_HEAP_SIZE
              value: "128M"  # Уменьшаем для Raspberry Pi
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /mnt/zookeeper-data
            type: DirectoryOrCreate