apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: chatverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8.2-debian-11-r0
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"  # Ключевое исправление!
            - name: ZOO_HEAP_SIZE
              value: "256"
            - name: ZOO_ENABLE_AUTH  # Добавляем явное отключение аутентификации
              value: "no"
          ports:
            - containerPort: 2181
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "echo srvr | nc localhost 2181 | grep Mode"
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /mnt/zookeeper-data
            type: DirectoryOrCreate