apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatverse-app
  namespace: chatverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatverse-app
  template:
    metadata:
      labels:
        app: chatverse-app
    spec:
      containers:
        - name: chatverse-app
          image: chatverse-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/chatverse
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgre
